$LOAD_PATH << File.join(File.dirname(__FILE__), "../..")
$LOAD_PATH << File.dirname(__FILE__)

# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require "simplecov"
SimpleCov.start

require "cucumber/rails"
require "webmock/cucumber"
WebMock.disable_net_connect!

require "capybara/poltergeist"
Capybara.javascript_driver = :poltergeist

require "sidekiq/testing"
Sidekiq::Testing.inline!

Before("@javascript") do
  WebMock.disable_net_connect!(allow_localhost: true)
end

After("@javascript") do
  WebMock.disable_net_connect!
end

Before("@disable_background_processing") do
  Sidekiq::Testing.fake!
end

After("@disable_background_processing") do
  Sidekiq::Testing.inline!
end

After do
  log_out
end

After do
  Timecop.return
end

# Capybara defaults to CSS3 selectors rather than XPath.
# If you'd prefer to use XPath, just uncomment this line and adjust any
# selectors in your step definitions to use the XPath syntax.
# Capybara.default_selector = :xpath

# By default, any exception happening in your Rails application will bubble up
# to Cucumber so that your scenario will fail. This is a different from how
# your application behaves in the production environment, where an error page will
# be rendered instead.
#
# Sometimes we want to override this default behaviour and allow Rails to rescue
# exceptions and display an error page (just like when the app is running in production).
# Typical scenarios where you want to do this is when you test your error pages.
# There are two ways to allow Rails to rescue exceptions:
#
# 1) Tag your scenario (or feature) with @allow-rescue
#
# 2) Set the value below to true. Beware that doing this globally is not
# recommended as it will mask a lot of errors for you!
#
ActionController::Base.allow_rescue = false

# Remove/comment out the lines below if your app doesn't have a database.
# For some databases (like MongoDB and CouchDB) you may need to use :truncation instead.
begin
  DatabaseCleaner.strategy = :truncation
rescue NameError
  raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
end

# You may also want to configure DatabaseCleaner to use different strategies for certain features and scenarios.
# See the DatabaseCleaner documentation for details. Example:
#
#   Before('@no-txn,@selenium,@culerity,@celerity,@javascript') do
#     # { :except => [:widgets] } may not do what you expect here
#     # as Cucumber::Rails::Database.javascript_strategy overrides
#     # this setting.
#     DatabaseCleaner.strategy = :truncation
#   end
#
#   Before('~@no-txn', '~@selenium', '~@culerity', '~@celerity', '~@javascript') do
#     DatabaseCleaner.strategy = :transaction
#   end
#

# Possible values are :truncation and :transaction
# The :transaction strategy is faster, but might give you threading problems.
# See https://github.com/cucumber/cucumber-rails/blob/master/features/choose_javascript_database_strategy.feature
Cucumber::Rails::Database.javascript_strategy = :truncation

require "rummager_helpers"
require "publishing_api_helpers"
require "organisations_api_helpers"
require "email_alert_api_helpers"
require "form_helpers"
require "document_helpers"
require "manual_helpers"
require "attachment_helpers"
require "file_fixture_helpers"
require "gds_sso_helpers"
require "access_control_helpers"
require "search_helpers"
require "mocks"
require "api_helpers"

require "aaib_report_helpers"
require "asylum_support_decision_helpers"
require "cma_case_helpers"
require "csg_helpers"
require "dsu_helpers"
require "employment_appeal_tribunal_decision_helpers"
require "employment_tribunal_decision_helpers"
require "esi_fund_helpers"
require "idf_helpers"
require "maib_report_helpers"
require "msa_helpers"
require "raib_report_helpers"
require "tax_tribunal_decision_helpers"
require "utaac_decision_helpers"
require "vehicle_recalls_and_faults_alert_helpers"

World(RummagerHelpers)
World(PublishingAPIHelpers)
World(OrganisationsAPIHelpers)
World(EmailAlertAPIHelpers)
World(FormHelpers)
World(DocumentHelpers)
World(ManualHelpers)
World(AttachmentHelpers)
World(FileFixtureHelpers)
World(GdsSsoHelpers)
World(AccessControlHelpers)
World(SearchHelpers)

World(AaibReportHelpers)
World(AsylumSupportDecisionHelpers)
World(CmaCaseHelpers)
World(CsgHelpers)
World(DsuHelpers)
World(EmploymentAppealTribunalDecisionHelpers)
World(EmploymentTribunalDecisionHelpers)
World(EsiFundHelpers)
World(IdfHelpers)
World(MaibReportHelpers)
World(MsaHelpers)
World(RaibReportHelpers)
World(TaxTribunalDecisionHelpers)
World(UtaacDecisionHelpers)
World(VehicleRecallsAndFaultsAlertHelpers)
